namespace ReUse.API.Responses;

/// <summary>
/// Standard error response returned by the API.
/// </summary>
/// <remarks>
/// This response format is used for <b>all errors</b> generated by the system,
/// including validation errors, business rule violations, authorization failures,
/// and unhandled server exceptions.
/// <para>
/// Errors are produced by the global exception middleware and are always returned
/// with <c>application/json</c> content type.
/// </para>
/// </remarks>
public class ErrorResponse
{
    /// <summary>
    /// A machine-readable error code that uniquely identifies the error type.
    /// </summary>
    /// <remarks>
    /// This value can be used by client applications to implement
    /// error-specific handling or localization.
    /// </remarks>
    /// <example>ERROR_CODE</example>
    public string Code { get; set; } = null!;

    /// <summary>
    /// A human-readable description of the error.
    /// </summary>
    /// <remarks>
    /// This message is safe to display to end users and explains
    /// why the request failed.
    /// </remarks>
    /// <example>msg</example>
    public string Message { get; init; } = null!;

    /// <summary>
    /// Optional collection of additional error details.
    /// </summary>
    /// <remarks>
    /// Used mainly for validation or identity-related errors.
    /// The structure of this field depends on the error type.
    /// <para>
    /// When not applicable, this field is <c>null</c>.
    /// </para>
    /// </remarks>
    public object? Errors { get; init; }
}